const ROLES = {
  STUDENT: 'student',
  RECRUITER: 'recruiter',
  ADMIN: 'admin',
}

const JOB_STATUSES = {
  DRAFT: 'draft',
  OPEN: 'open',
  CLOSED: 'closed',
}

const JOB_MODERATION_STATUSES = {
  APPROVED: 'approved',
  FLAGGED: 'flagged',
  REJECTED: 'rejected',
}

const REPORT_STATUSES = {
  PENDING: 'pending',
  RESOLVED: 'resolved',
}

const APPLICATION_STATUSES = {
  PENDING: 'pending',
  SHORTLISTED: 'shortlisted',
  INTERVIEW: 'interview',
  REJECTED: 'rejected',
  OFFERED: 'offered',
  ACCEPTED: 'accepted',
  INTERVIEW_ACCEPTED: 'interview_accepted',
  REFUSED: 'refused',
}

const APPLICATION_STATUS_FLOW = {
  [APPLICATION_STATUSES.PENDING]: [
    APPLICATION_STATUSES.SHORTLISTED,
    APPLICATION_STATUSES.INTERVIEW,
    APPLICATION_STATUSES.REJECTED,
  ],
  [APPLICATION_STATUSES.SHORTLISTED]: [
    APPLICATION_STATUSES.INTERVIEW,
    APPLICATION_STATUSES.REJECTED,
    APPLICATION_STATUSES.OFFERED,
  ],
  [APPLICATION_STATUSES.INTERVIEW]: [
  APPLICATION_STATUSES.INTERVIEW_ACCEPTED,
  APPLICATION_STATUSES.REJECTED,
],

[APPLICATION_STATUSES.INTERVIEW_ACCEPTED]: [
  APPLICATION_STATUSES.OFFERED,
  APPLICATION_STATUSES.REJECTED,
],
  [APPLICATION_STATUSES.REJECTED]: [],
  [APPLICATION_STATUSES.OFFERED]: [],
}

module.exports = {
  ROLES,
  JOB_STATUSES,
  JOB_MODERATION_STATUSES,
  REPORT_STATUSES,
  APPLICATION_STATUSES,
  APPLICATION_STATUS_FLOW,
}
